### ISSUE TITLE
java.lang.IllegalStateException: Dependency "use_energy_saving_mode" not found for preference "use_log_energy_saving_mode" (title: "Log: Energiesparmodus"

### ISSUE THREAD

**Issue by davidgraeff** [davidgraeff/Android-NetPowerctrl#42]
``` bash
java.lang.IllegalStateException: Dependency "use_energy_saving_mode" not found for preference "use_log_energy_saving_mode" (title: "Log: Energiesparmodus"
at android.preference.Preference.registerDependency(Preference.java:1163)
at android.preference.Preference.onAttachedToActivity(Preference.java:1152)
at android.preference.PreferenceGroup.onAttachedToActivity(PreferenceGroup.java:277)
at android.preference.PreferenceGroup.onAttachedToActivity(PreferenceGroup.java:277)
at android.preference.PreferenceScreen.bind(PreferenceScreen.java:147)
at android.preference.PreferenceFragment.bindPreferences(PreferenceFragment.java:330)
at android.preference.PreferenceFragment.onActivityCreated(PreferenceFragment.java:171)
at android.app.Fragment.performActivityCreated(Fragment.java:1785)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:922)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1106)
at android.app.BackStackRecord.run(BackStackRecord.java:690)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1571)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5872)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by artshell** [comment]
you should call setDependency after you have finished calling addPreference 

private static final String PARENT_CHECKBOX_PREFERENCE = "parent_checkbox_preference";
 
    @Override 
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        PreferenceScreen root = getPreferenceManager().createPreferenceScreen(this);
        setPreferenceScreen(root); //-----------------
        populatePreferenceHierarchy(root); //-----------
    } 
 
private void populatePreferenceHierarchy(PreferenceScreen pScreenRoot) {
        // Preference attributes 
        PreferenceCategory prefAttrsCat = new PreferenceCategory(this);
        prefAttrsCat.setTitle("preference_attributes");
        pScreenRoot.addPreference(prefAttrsCat);
 
        // Visual parent toggle preference 
        CheckBoxPreference parentCheckBoxPref = new CheckBoxPreference(this);
        parentCheckBoxPref.setKey(PARENT_CHECKBOX_PREFERENCE);
        parentCheckBoxPref.setTitle("title_parent_preference");
        parentCheckBoxPref.setSummary("summary_parent_preference");
        prefAttrsCat.addPreference(parentCheckBoxPref);
 
 
        // Visual child toggle preference 
        // See res/values/attrs.xml for the <declare-styleable> that defines TogglePrefAttrs. 
        TypedArray typeA = obtainStyledAttributes(R.styleable.TogglePrefAttrs);
        CheckBoxPreference childCheckBoxPref = new CheckBoxPreference(this);
        childCheckBoxPref.setKey("child_checkbox_preference");
        childCheckBoxPref.setTitle("title_child_preference");
        childCheckBoxPref.setSummary("summary_child_preference");
        childCheckBoxPref.setLayoutResource(typeA.getResourceId(R.styleable.TogglePrefAttrs_android_preferenceLayoutChild, 0));
        prefAttrsCat.addPreference(childCheckBoxPref); // ------
        childCheckBoxPref.setDependency(PARENT_CHECKBOX_PREFERENCE);  //----------
 
        typeA.recycle();
}

**Comment by davidgraeff** [comment]
Thanks :)
